import { QRFrame, FrameCategory } from '../types';

export interface FrameCategoryOption {
  id: FrameCategory;
  label: string;
  icon: string;
}

export const FRAME_CATEGORIES: FrameCategoryOption[] = [
  { id: 'all', label: 'Todos', icon: '✨' },
  { id: 'professions', label: 'Profesiones', icon: '👷‍♂️' },
  { id: 'love', label: 'Amor & Boda', icon: '💖' },
  { id: 'events', label: 'Fiestas & Eventos', icon: '🎂' },
  { id: 'business', label: 'Comercio & Tiendas', icon: '🛍️' },
  { id: 'hospitality', label: 'Gastronomía & Bares', icon: '🍸' },
  { id: 'nature', label: 'Naturaleza & Flores', icon: '🌸' },
  { id: 'creative', label: 'Creativo & Arte', icon: '🎨' },
  { id: 'standard', label: 'Estándar', icon: '📐' },
  { id: 'custom', label: 'Creados por Admin', icon: '⭐' }
];

export const FRAMES: QRFrame[] = [
  // --- STANDARD FRAMES ---
  {
    id: 'none',
    name: 'Clásico',
    category: 'standard',
    description: 'Sin marco exterior',
    viewBox: '0 0 100 100',
    qrSize: 96,
    qrX: 2,
    qrY: 2,
    hasText: false,
    textPosition: 'none',
    badgeStyle: 'none'
  },
  {
    id: 'bottom-banner',
    name: 'Banner Abajo',
    category: 'standard',
    description: 'Marco con banner inferior y flecha indicadora',
    viewBox: '0 0 100 128',
    qrSize: 84,
    qrX: 8,
    qrY: 8,
    hasText: true,
    defaultText: 'ESCANÉAME',
    textPosition: 'bottom',
    badgeStyle: 'banner',
    borderRadius: 8
  },
  {
    id: 'bottom-pill',
    name: 'Cápsula Flotante',
    category: 'standard',
    description: 'Marco redondeado con píldora flotante',
    viewBox: '0 0 100 126',
    qrSize: 80,
    qrX: 10,
    qrY: 8,
    hasText: true,
    defaultText: 'SCAN ME',
    textPosition: 'bottom',
    badgeStyle: 'pill',
    borderRadius: 14
  },
  {
    id: 'top-banner',
    name: 'Banner Superior',
    category: 'standard',
    description: 'Encabezado superior destacado',
    viewBox: '0 0 100 126',
    qrSize: 82,
    qrX: 9,
    qrY: 34,
    hasText: true,
    defaultText: 'ESCANÉAME',
    textPosition: 'top',
    badgeStyle: 'banner',
    borderRadius: 8
  },
  {
    id: 'chat-bubble',
    name: 'Burbuja Chat',
    category: 'standard',
    description: 'Burbuja de chat interactiva',
    viewBox: '0 0 100 128',
    qrSize: 78,
    qrX: 11,
    qrY: 8,
    hasText: true,
    defaultText: '¡ÁBREME!',
    textPosition: 'bottom',
    badgeStyle: 'bubble',
    borderRadius: 16
  },
  {
    id: 'smartphone',
    name: 'Smartphone',
    category: 'standard',
    description: 'Silueta de smartphone moderno',
    viewBox: '0 0 100 134',
    qrSize: 76,
    qrX: 12,
    qrY: 18,
    hasText: true,
    defaultText: 'ABRIR EN MÓVIL',
    textPosition: 'bottom',
    badgeStyle: 'phone',
    borderRadius: 18
  },
  {
    id: 'clipboard',
    name: 'Tarjeta / Clip',
    category: 'standard',
    description: 'Hoja de notas con clip superior',
    viewBox: '0 0 100 128',
    qrSize: 78,
    qrX: 11,
    qrY: 18,
    hasText: true,
    defaultText: 'INFO & MENÚ',
    textPosition: 'bottom',
    badgeStyle: 'clipboard',
    borderRadius: 8
  },
  {
    id: 'polaroid',
    name: 'Polaroid Foto',
    category: 'standard',
    description: 'Marco fotográfico instantáneo',
    viewBox: '0 0 100 126',
    qrSize: 80,
    qrX: 10,
    qrY: 10,
    hasText: true,
    defaultText: 'FOTOS & RECUERDOS',
    textPosition: 'bottom',
    badgeStyle: 'polaroid',
    borderRadius: 4
  },
  {
    id: 'circle-badge',
    name: 'Medallón Circular',
    category: 'standard',
    description: 'Marco circular con badge inferior',
    viewBox: '0 0 100 120',
    qrSize: 74,
    qrX: 13,
    qrY: 8,
    hasText: true,
    defaultText: 'SCAN ME',
    textPosition: 'bottom',
    badgeStyle: 'circle',
    borderRadius: 50
  },
  {
    id: 'tech-brackets',
    name: 'Tech Cyber HUD',
    category: 'standard',
    description: 'Esquinas cibernéticas modernas',
    viewBox: '0 0 100 100',
    qrSize: 78,
    qrX: 11,
    qrY: 11,
    hasText: false,
    textPosition: 'none',
    badgeStyle: 'brackets'
  },
  {
    id: 'simple-border',
    name: 'Borde Minimal',
    category: 'standard',
    description: 'Borde perimetral elegante',
    viewBox: '0 0 100 100',
    qrSize: 84,
    qrX: 8,
    qrY: 8,
    hasText: false,
    textPosition: 'none',
    badgeStyle: 'none',
    borderRadius: 12
  },

  // --- PROFESSIONS & TRADES ---
  {
    id: 'construction-helmet',
    name: 'Constructor / Obras',
    category: 'professions',
    description: 'Casco de seguridad de obra y marco industrial',
    viewBox: '0 0 100 132',
    qrSize: 76,
    qrX: 12,
    qrY: 26,
    hasText: true,
    defaultText: 'PROYECTO & PLANOS',
    textPosition: 'bottom',
    badgeStyle: 'banner',
    silhouetteShape: 'rounded',
    topIcon: '👷‍♂️',
    themeColor: '#eab308',
    accentColor: '#6b21a8'
  },
  {
    id: 'medical-cross',
    name: 'Médico / Salud',
    category: 'professions',
    description: 'Cruz médica y marco para doctores y clínicas',
    viewBox: '0 0 100 130',
    qrSize: 78,
    qrX: 11,
    qrY: 24,
    hasText: true,
    defaultText: 'CITAS & CONSULTAS',
    textPosition: 'bottom',
    badgeStyle: 'pill',
    silhouetteShape: 'rounded',
    topIcon: '🩺',
    themeColor: '#0284c7',
    accentColor: '#e0f2fe'
  },
  {
    id: 'chef-restaurant',
    name: 'Chef & Cocina',
    category: 'professions',
    description: 'Gorro de chef y detalles gourmet',
    viewBox: '0 0 100 132',
    qrSize: 78,
    qrX: 11,
    qrY: 26,
    hasText: true,
    defaultText: 'RECETAS & MENÚ',
    textPosition: 'bottom',
    badgeStyle: 'pill',
    silhouetteShape: 'rounded',
    topIcon: '👨‍🍳',
    themeColor: '#dc2626',
    accentColor: '#fee2e2'
  },
  {
    id: 'legal-lawyer',
    name: 'Abogado / Legal',
    category: 'professions',
    description: 'Balanza de la justicia y marco solemne',
    viewBox: '0 0 100 130',
    qrSize: 78,
    qrX: 11,
    qrY: 24,
    hasText: true,
    defaultText: 'ASESORÍA LEGAL',
    textPosition: 'bottom',
    badgeStyle: 'banner',
    silhouetteShape: 'rounded',
    topIcon: '⚖️',
    themeColor: '#1e293b',
    accentColor: '#f8fafc'
  },
  {
    id: 'artist-palette',
    name: 'Artista & Diseño',
    category: 'professions',
    description: 'Paleta de pintor, pinceles y reglas creativas',
    viewBox: '0 0 100 130',
    qrSize: 76,
    qrX: 12,
    qrY: 24,
    hasText: true,
    defaultText: 'PORTAFOLIO ARTE',
    textPosition: 'bottom',
    badgeStyle: 'pill',
    silhouetteShape: 'rounded',
    topIcon: '🎨',
    themeColor: '#8b5cf6',
    accentColor: '#f3e8ff'
  },
  {
    id: 'education-grad',
    name: 'Docencia & Cursos',
    category: 'professions',
    description: 'Birrete de graduación para academias y certificados',
    viewBox: '0 0 100 130',
    qrSize: 78,
    qrX: 11,
    qrY: 24,
    hasText: true,
    defaultText: 'CURSO & DIPLOMA',
    textPosition: 'bottom',
    badgeStyle: 'banner',
    silhouetteShape: 'rounded',
    topIcon: '🎓',
    themeColor: '#059669',
    accentColor: '#d1fae5'
  },

  // --- LOVE & WEDDINGS ---
  {
    id: 'heart-burst',
    name: 'San Valentín Amor',
    category: 'love',
    description: 'Explosión de corazones flotantes y destellos románticos',
    viewBox: '0 0 100 134',
    qrSize: 76,
    qrX: 12,
    qrY: 20,
    hasText: true,
    defaultText: 'MY UNIVERSE',
    textPosition: 'bottom',
    badgeStyle: 'pill',
    silhouetteShape: 'rounded',
    cornerStyle: 'hearts',
    topIcon: '💖',
    themeColor: '#ec4899',
    accentColor: '#fce7f3'
  },
  {
    id: 'cupid-arrows',
    name: 'Flechas de Cupido',
    category: 'love',
    description: 'Marco punteado con flechas y corazones en las esquinas',
    viewBox: '0 0 100 128',
    qrSize: 78,
    qrX: 11,
    qrY: 10,
    hasText: true,
    defaultText: 'LOVE STORY',
    textPosition: 'bottom',
    badgeStyle: 'pill',
    silhouetteShape: 'rounded',
    cornerStyle: 'arrows',
    themeColor: '#f43f5e',
    accentColor: '#fff1f2'
  },
  {
    id: 'hanging-hearts',
    name: 'Corazones Colgantes',
    category: 'love',
    description: 'Guirnalda de corazones móviles colgando',
    viewBox: '0 0 100 136',
    qrSize: 76,
    qrX: 12,
    qrY: 10,
    hasText: true,
    defaultText: 'NUESTRA BODA',
    textPosition: 'bottom',
    badgeStyle: 'pill',
    bottomStyle: 'hanging_hearts',
    themeColor: '#db2777',
    accentColor: '#fdf2f8'
  },
  {
    id: 'heart-silhouette',
    name: 'Silueta Corazón',
    category: 'love',
    description: 'Marco con silueta de corazón envolvente',
    viewBox: '0 0 100 128',
    qrSize: 74,
    qrX: 13,
    qrY: 14,
    hasText: true,
    defaultText: 'TE AMO',
    textPosition: 'bottom',
    badgeStyle: 'pill',
    silhouetteShape: 'heart',
    themeColor: '#e11d48',
    accentColor: '#ffe4e6'
  },

  // --- EVENTS & CELEBRATIONS ---
  {
    id: 'birthday-balloons',
    name: 'Globos de Cumpleaños',
    category: 'events',
    description: 'Globos festivos y pancarta de Feliz Cumpleaños',
    viewBox: '0 0 100 134',
    qrSize: 76,
    qrX: 12,
    qrY: 26,
    hasText: true,
    defaultText: '¡FELIZ CUMPLE!',
    textPosition: 'bottom',
    badgeStyle: 'banner',
    topIcon: '🎈',
    cornerStyle: 'confetti',
    themeColor: '#8b5cf6',
    accentColor: '#fdf4ff'
  },
  {
    id: 'mardi-gras-carnival',
    name: 'Carnaval & Fiesta',
    category: 'events',
    description: 'Máscara veneciana, confeti y notas musicales',
    viewBox: '0 0 100 134',
    qrSize: 76,
    qrX: 12,
    qrY: 26,
    hasText: true,
    defaultText: 'FIESTA VIP',
    textPosition: 'bottom',
    badgeStyle: 'pill',
    topIcon: '🎭',
    cornerStyle: 'confetti',
    themeColor: '#9333ea',
    accentColor: '#faf5ff'
  },
  {
    id: 'christmas-holly',
    name: 'Navidad & Muérdago',
    category: 'events',
    description: 'Ramas de pino perenne, acebo y copos de nieve',
    viewBox: '0 0 100 130',
    qrSize: 76,
    qrX: 12,
    qrY: 12,
    hasText: true,
    defaultText: 'FELIZ NAVIDAD',
    textPosition: 'bottom',
    badgeStyle: 'pill',
    cornerStyle: 'pine_holly',
    themeColor: '#15803d',
    accentColor: '#f0fdf4'
  },
  {
    id: 'holiday-gift-box',
    name: 'Caja de Regalo',
    category: 'events',
    description: 'Marco con lazo decorativo y cinta de obsequio',
    viewBox: '0 0 100 132',
    qrSize: 76,
    qrX: 12,
    qrY: 14,
    hasText: true,
    defaultText: 'TU REGALO AQUÍ',
    textPosition: 'bottom',
    badgeStyle: 'banner',
    bottomStyle: 'gift_ribbon',
    topIcon: '🎁',
    themeColor: '#b91c1c',
    accentColor: '#fef2f2'
  },
  {
    id: 'chinese-lantern',
    name: 'Faroles Orientales',
    category: 'events',
    description: 'Faroles festivos colgantes y detalles dorados',
    viewBox: '0 0 100 134',
    qrSize: 76,
    qrX: 12,
    qrY: 24,
    hasText: true,
    defaultText: 'BUENA FORTUNA',
    textPosition: 'bottom',
    badgeStyle: 'banner',
    cornerStyle: 'lanterns',
    topIcon: '🏮',
    themeColor: '#dc2626',
    accentColor: '#fef08a'
  },

  // --- BUSINESS & COMMERCE ---
  {
    id: 'shopping-bag',
    name: 'Bolsa de Compras',
    category: 'business',
    description: 'Silueta de bolsa de tienda con asas y etiqueta de compra',
    viewBox: '0 0 100 136',
    qrSize: 76,
    qrX: 12,
    qrY: 26,
    hasText: true,
    defaultText: 'SHOP NOW!',
    textPosition: 'bottom',
    badgeStyle: 'banner',
    silhouetteShape: 'shopping_bag',
    topIcon: '🛍️',
    themeColor: '#0f766e',
    accentColor: '#ccfbf1'
  },
  {
    id: 'discount-ticket',
    name: 'Ticket & Cupón',
    category: 'business',
    description: 'Silueta de entrada con perforaciones laterales',
    viewBox: '0 0 100 128',
    qrSize: 76,
    qrX: 12,
    qrY: 12,
    hasText: true,
    defaultText: 'DESCUENTO 20%',
    textPosition: 'bottom',
    badgeStyle: 'ticket',
    silhouetteShape: 'ticket',
    themeColor: '#ea580c',
    accentColor: '#ffedd5'
  },
  {
    id: 'invitation-envelope',
    name: 'Sobre & Invitación',
    category: 'business',
    description: 'Carta postal abierta con flores e invitación',
    viewBox: '0 0 100 132',
    qrSize: 76,
    qrX: 12,
    qrY: 24,
    hasText: true,
    defaultText: 'VER INVITACIÓN',
    textPosition: 'bottom',
    badgeStyle: 'pill',
    silhouetteShape: 'envelope',
    topIcon: '✉️',
    themeColor: '#4338ca',
    accentColor: '#e0e7ff'
  },

  // --- HOSPITALITY & GASTRONOMY ---
  {
    id: 'margarita-cocktail',
    name: 'Cóctel & Lima',
    category: 'hospitality',
    description: 'Copa de cóctel y rodaja fresca de lima en la esquina',
    viewBox: '0 0 100 132',
    qrSize: 76,
    qrX: 12,
    qrY: 22,
    hasText: true,
    defaultText: 'CARTA DE TRAGOS',
    textPosition: 'bottom',
    badgeStyle: 'pill',
    cornerStyle: 'cocktail_lime',
    topIcon: '🍸',
    themeColor: '#65a30d',
    accentColor: '#ecfccb'
  },
  {
    id: 'coffee-cafe',
    name: 'Cafetería & Bar',
    category: 'hospitality',
    description: 'Taza humeante y ambiente de cafetería moderna',
    viewBox: '0 0 100 130',
    qrSize: 78,
    qrX: 11,
    qrY: 24,
    hasText: true,
    defaultText: 'MENÚ CAFÉ',
    textPosition: 'bottom',
    badgeStyle: 'pill',
    topIcon: '☕',
    themeColor: '#78350f',
    accentColor: '#fef3c7'
  },

  // --- NATURE & BOTANICAL ---
  {
    id: 'floral-wreath',
    name: 'Corona Floral',
    category: 'nature',
    description: 'Guirnalda de flores pastel y hojas botánicas',
    viewBox: '0 0 100 130',
    qrSize: 76,
    qrX: 12,
    qrY: 14,
    hasText: true,
    defaultText: 'FLORES & BODA',
    textPosition: 'bottom',
    badgeStyle: 'pill',
    cornerStyle: 'flowers',
    themeColor: '#ec4899',
    accentColor: '#fdf2f8'
  },
  {
    id: 'autumn-leaves',
    name: 'Hojas de Otoño',
    category: 'nature',
    description: 'Hojas doradas de arce y bellotas otoñales',
    viewBox: '0 0 100 130',
    qrSize: 76,
    qrX: 12,
    qrY: 14,
    hasText: true,
    defaultText: 'OTOÑO 2026',
    textPosition: 'bottom',
    badgeStyle: 'pill',
    cornerStyle: 'autumn_leaves',
    themeColor: '#c2410c',
    accentColor: '#ffedd5'
  },
  {
    id: 'lavender-garden',
    name: 'Lavanda & Mariposa',
    category: 'nature',
    description: 'Flores de lavanda silvestre y mariposa',
    viewBox: '0 0 100 130',
    qrSize: 76,
    qrX: 12,
    qrY: 14,
    hasText: true,
    defaultText: 'AROMAS & SPA',
    textPosition: 'bottom',
    badgeStyle: 'pill',
    cornerStyle: 'flowers',
    topIcon: '🦋',
    themeColor: '#7c3aed',
    accentColor: '#ede9fe'
  },

  // --- CREATIVE & DOCUMENTS ---
  {
    id: 'legal-parchment',
    name: 'Pergamino & Pluma',
    category: 'creative',
    description: 'Documento apergaminado y pluma de caligrafía antigua',
    viewBox: '0 0 100 134',
    qrSize: 76,
    qrX: 12,
    qrY: 14,
    hasText: true,
    defaultText: 'DOCUMENTO OFICIAL',
    textPosition: 'bottom',
    badgeStyle: 'banner',
    silhouetteShape: 'parchment',
    bottomStyle: 'quill_ink',
    themeColor: '#854d0e',
    accentColor: '#fefce8'
  },
  {
    id: 'oriental-arch',
    name: 'Cúpula & Mezquita',
    category: 'creative',
    description: 'Arco ornamental con farolillo nocturno',
    viewBox: '0 0 100 134',
    qrSize: 76,
    qrX: 12,
    qrY: 26,
    hasText: true,
    defaultText: 'ARABIC NIGHTS',
    textPosition: 'bottom',
    badgeStyle: 'banner',
    silhouetteShape: 'oriental_arch',
    topIcon: '🕌',
    themeColor: '#1e3a8a',
    accentColor: '#fef08a'
  },
  {
    id: 'red-rosette',
    name: 'Roseta Festoneada',
    category: 'creative',
    description: 'Medallón floral festoneado con crestas circulares',
    viewBox: '0 0 100 130',
    qrSize: 74,
    qrX: 13,
    qrY: 14,
    hasText: true,
    defaultText: 'CALIDAD PREMIUM',
    textPosition: 'bottom',
    badgeStyle: 'pill',
    silhouetteShape: 'rosette',
    topIcon: '🏵️',
    themeColor: '#b91c1c',
    accentColor: '#fee2e2'
  }
];

export const FONT_FAMILIES = {
  sans: 'Inter, system-ui, -apple-system, sans-serif',
  serif: 'Georgia, Cambria, "Times New Roman", serif',
  mono: '"Courier New", Courier, monospace',
  display: '"Impact", "Arial Black", sans-serif',
  handwriting: '"Brush Script MT", "Caveat", cursive, sans-serif'
};

