import { QRTemplate, TemplateCategory } from '../types';

export interface TemplateCategoryOption {
  id: TemplateCategory;
  label: string;
  icon: string;
}

export const TEMPLATE_CATEGORIES: TemplateCategoryOption[] = [
  { id: 'all', label: 'Todas las Plantillas', icon: '✨' },
  { id: 'reviews', label: 'Google Maps & Reseñas', icon: '⭐' },
  { id: 'hospitality', label: 'Restaurantes & Bares', icon: '🍽️' },
  { id: 'wifi', label: 'Conexión Wi-Fi', icon: '📶' },
  { id: 'social', label: 'Redes Sociales', icon: '📱' },
  { id: 'payments', label: 'Pagos & Propinas', icon: '💳' },
  { id: 'events', label: 'Bodas & Eventos', icon: '💍' },
  { id: 'retail', label: 'Tiendas & Promos', icon: '🏷️' },
  { id: 'professional', label: 'Profesionales & Citas', icon: '💼' }
];

export const PRESET_TEMPLATES: QRTemplate[] = [
  // --- 1. GOOGLE REVIEWS & VALORACIONES ---
  {
    id: 'google-acrylic-wood',
    name: 'Google Reseñas - Placa Acrílica con Pie de Madera (Foto 2)',
    subtitle: 'Atril blanco con logo oficial de Google, 5 estrellas y pie de pino',
    description: 'El soporte físico más utilizado en mesas, barras y mostradores. Idéntico al expositor acrílico con peana de madera natural.',
    category: 'reviews',
    categoryLabel: 'Google & Reseñas',
    badge: '⭐ Atril Mostrador',
    icon: '🌟',
    popular: true,
    previewColor: '#ea4335',
    previewBg: '#ffffff',
    helperType: 'google_review',
    sampleUrl: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
    tips: 'Para conseguir tu enlace oficial: Abre Google Maps > Busca tu negocio > Toca "Conseguir más reseñas" o "Compartir perfil" y pega el link corto.',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'Google Reseñas - Placa Acrílica',
      targetContent: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
      value: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
      fgColor: '#0f172a',
      bgColor: '#ffffff',
      frameId: 'none',
      showCard: true,
      cardPosition: 'bottom',
      cardTitle: 'Valorános',
      cardSubtitle: '5 Estrellas en Google Maps',
      cardInstructions: 'Escanea QR',
      cardBgColor: '#ffffff',
      cardTextColor: '#0f172a',
      cardShowStars: true,
      cardShowWoodBase: true,
      cardTheme: 'google_acrylic_wood'
    }
  },
  {
    id: 'google-black-card',
    name: 'Google Reseñas - Tarjeta Negra Mate PVC (Foto 3)',
    subtitle: 'Tarjeta negra con tiras de los 4 colores de Google y recuadro para tu logo',
    description: 'Diseño elegante estilo tarjeta de crédito / NFC de Google Review con las 4 franjas icónicas (Rojo, Amarillo, Azul, Verde).',
    category: 'reviews',
    categoryLabel: 'Google & Reseñas',
    badge: '🖤 Tarjeta Negra',
    icon: '💳',
    popular: true,
    previewColor: '#4285F4',
    previewBg: '#18181b',
    helperType: 'google_review',
    sampleUrl: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
    tips: 'Ideal para entregar a clientes satisfechos al pedir la cuenta, o colocar junto al datáfono de cobro.',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'Google Review - Tarjeta Negra Mate',
      targetContent: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
      value: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
      fgColor: '#000000',
      bgColor: '#ffffff',
      frameId: 'none',
      showCard: true,
      cardPosition: 'bottom',
      cardTitle: 'Tu opinión en Google',
      cardSubtitle: 'Escanea el código QR o toca con tu celular',
      cardInstructions: 'Toma 10 segundos',
      cardCustomLogoText: 'Pon tu logo / Tu Negocio',
      cardBgColor: '#18181b',
      cardTextColor: '#ffffff',
      cardShowStars: true,
      cardTheme: 'google_black_card'
    }
  },
  {
    id: 'google-geometric-card',
    name: 'Google Reseñas - Tarjeta Geométrica Multicolor (Foto 1)',
    subtitle: 'Diseño moderno con bloques diagonales azul, verde, amarillo y rojo',
    description: 'Máxima atracción visual con los colores corporativos oficiales de Google y mensaje "Tu opinión nos importa".',
    category: 'reviews',
    categoryLabel: 'Google & Reseñas',
    badge: '🎨 Multicolor',
    icon: '✨',
    popular: true,
    previewColor: '#34A853',
    previewBg: '#2563EB',
    helperType: 'google_review',
    sampleUrl: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
    tips: 'Coloca este cartel en la barra o en la recepción de tu local para captar la atención inmediatamente.',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'Google Reseñas - Tarjeta Geométrica',
      targetContent: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
      value: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
      fgColor: '#0f172a',
      bgColor: '#ffffff',
      frameId: 'none',
      showCard: true,
      cardPosition: 'bottom',
      cardTitle: 'Califícanos en Google',
      cardSubtitle: 'Tu opinión nos importa',
      cardCta: 'Escanea',
      cardBgColor: '#2563eb',
      cardTextColor: '#ffffff',
      cardShowStars: true,
      cardTheme: 'google_geometric_card'
    }
  },
  {
    id: 'google-review-compact',
    name: 'Google Maps - Sticker Adhesivo',
    subtitle: 'Formato sticker cuadrado / circular para cristaleras y vitrinas',
    description: 'Diseño directo con marco perimetral azul Google y llamada urgente a valorar el local.',
    category: 'reviews',
    categoryLabel: 'Google & Reseñas',
    badge: '⭐ Sticker Google',
    icon: '🏷️',
    previewColor: '#1a73e8',
    previewBg: '#ffffff',
    helperType: 'google_review',
    sampleUrl: 'https://g.page/r/sample/review',
    tips: 'Ideal para colocar en la puerta de salida, cerca del datáfono o en el ticket de compra.',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'Google Maps Sticker Reseña',
      targetContent: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
      value: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
      fgColor: '#0f172a',
      bgColor: '#ffffff',
      frameId: 'bottom-banner',
      frameText: '5 ESTRELLAS',
      frameColor: '#f59e0b',
      frameTextColor: '#ffffff',
      frameFont: 'sans',
      showCard: true,
      cardPosition: 'bottom',
      cardTitle: '¿Te ha gustado nuestro servicio?',
      cardSubtitle: 'Califícanos en Google Maps con 5 estrellas ⭐⭐⭐⭐⭐',
      cardInstructions: 'Toma solo 10 segundos y nos ayuda enormemente',
      cardCta: 'Opiniones 100% reales de clientes',
      cardBgColor: '#ffffff',
      cardTextColor: '#0f172a',
      cardShowStars: true,
      cardTheme: 'google_review'
    }
  },
  {
    id: 'google-review-dark-luxury',
    name: 'Google Review - Black & Gold Luxury',
    subtitle: 'Diseño premium en fondo oscuro con acentos dorados',
    description: 'Perfecto para restaurantes de alta cocina, hoteles boutique, barberías prémium o centros estéticos.',
    category: 'reviews',
    categoryLabel: 'Google & Reseñas',
    badge: '👑 Dark Luxury',
    icon: '✨',
    previewColor: '#f59e0b',
    previewBg: '#0f172a',
    helperType: 'google_review',
    sampleUrl: 'https://g.page/r/sample/review',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'Google Review Luxury Dark',
      targetContent: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
      value: 'https://search.google.com/local/writereview?placeid=ChIJN1t_tDeuEmsRUsoyG83frY4',
      fgColor: '#f8fafc',
      bgColor: '#0f172a',
      frameId: 'bottom-pill',
      frameText: 'CALIFÍCANOS',
      frameColor: '#f59e0b',
      frameTextColor: '#0f172a',
      frameFont: 'serif',
      showCard: true,
      cardPosition: 'flyer',
      cardTitle: 'Tu opinión define nuestra excelencia',
      cardSubtitle: 'Valora tu experiencia exclusiva en Google ⭐⭐⭐⭐⭐',
      cardInstructions: 'Apunta la cámara de tu móvil para calificar nuestro servicio',
      cardCta: 'Gracias por formar parte de nuestra comunidad',
      cardBgColor: '#0f172a',
      cardTextColor: '#f8fafc',
      cardShowStars: true,
      cardBadgeText: 'PREMIUM EXPERIENCE',
      cardTheme: 'google_review'
    }
  },
  {
    id: 'tripadvisor-stand',
    name: 'TripAdvisor - Opiniones de Viajeros',
    subtitle: 'Verde característico TripAdvisor para hoteles y gastronomía',
    description: 'Incentiva a turistas nacionales e internacionales a dejar su recomendación verificada.',
    category: 'reviews',
    categoryLabel: 'Google & Reseñas',
    badge: '🦉 TripAdvisor',
    icon: '🌿',
    previewColor: '#00af87',
    previewBg: '#ffffff',
    helperType: 'custom_url',
    sampleUrl: 'https://www.tripadvisor.com/UserReview',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'TripAdvisor Opiniones',
      targetContent: 'https://www.tripadvisor.com/UserReview',
      value: 'https://www.tripadvisor.com/UserReview',
      fgColor: '#052e26',
      bgColor: '#ffffff',
      frameId: 'bottom-banner',
      frameText: 'RECOMIÉNDANOS',
      frameColor: '#00af87',
      frameTextColor: '#ffffff',
      frameFont: 'sans',
      showCard: true,
      cardPosition: 'flyer',
      cardTitle: '¿Has disfrutado de tu estancia?',
      cardSubtitle: 'Comparte tu recomendación en TripAdvisor ⭐⭐⭐⭐⭐',
      cardInstructions: '1. Escanea • 2. Escribe tu opinión • 3. Ayuda a otros viajeros',
      cardCta: 'Certificado de Excelencia de Viajeros',
      cardBgColor: '#ffffff',
      cardTextColor: '#052e26',
      cardShowStars: true,
      cardBadgeText: 'TRIPADVISOR',
      cardTheme: 'tripadvisor'
    }
  },

  // --- 2. RESTAURANTES & GASTRONOMÍA ---
  {
    id: 'restaurant-menu-stand',
    name: 'Menú Digital & Carta de Mesa',
    subtitle: 'El clásico atril para mesas con acceso instantáneo a la carta',
    description: 'Reduce costos de impresión, permite modificar tus platos en tiempo real y ofrece fotos atractivas.',
    category: 'hospitality',
    categoryLabel: 'Restaurantes & Bares',
    badge: '🍽️ Carta Digital',
    icon: '🍕',
    popular: true,
    previewColor: '#dc2626',
    previewBg: '#ffffff',
    helperType: 'custom_url',
    sampleUrl: 'https://mimenu-online.com/carta',
    config: {
      contentType: 'URL',
      isDynamic: true,
      title: 'Menú Digital Restaurante',
      dynamicTitle: 'Carta & Especialidades del Chef',
      dynamicDescription: 'Entrantes, platos principales, pastas, carnes y sugerencias del día con ingredientes frescos.',
      dynamicButtonText: 'Ver Carta Completa (PDF/Web)',
      targetContent: 'https://mimenu-online.com/carta',
      value: 'https://mimenu-online.com/carta',
      fgColor: '#7f1d1d',
      bgColor: '#ffffff',
      frameId: 'chef-restaurant',
      frameText: 'VER MENÚ',
      frameColor: '#dc2626',
      frameTextColor: '#ffffff',
      frameFont: 'sans',
      showCard: true,
      cardPosition: 'flyer',
      cardTitle: 'Menú Digital sin Contacto',
      cardSubtitle: 'Explora nuestra carta, alérgenos y sugerencias del chef',
      cardInstructions: 'Escanea el código con tu móvil para ordenar al instante',
      cardCta: '¡Buen provecho! Pregunta a tu camarero por el menú del día',
      cardBgColor: '#ffffff',
      cardTextColor: '#1e293b',
      cardBadgeText: 'GASTRONOMÍA'
    }
  },
  {
    id: 'cocktail-lounge-bar',
    name: 'Carta de Cócteles & Vinos',
    subtitle: 'Diseño nocturno sofisticado para coctelerías y bodegas',
    description: 'Destaca tragos de autor, gin tonics, maridajes y carta de bebidas en barras y veladores.',
    category: 'hospitality',
    categoryLabel: 'Restaurantes & Bares',
    badge: '🍸 Bar & Cócteles',
    icon: '🥂',
    previewColor: '#d97706',
    previewBg: '#111827',
    helperType: 'custom_url',
    sampleUrl: 'https://mibar.com/cocteles',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'Carta de Cócteles y Tragos',
      targetContent: 'https://mibar.com/cocteles',
      value: 'https://mibar.com/cocteles',
      fgColor: '#fef3c7',
      bgColor: '#111827',
      frameId: 'bottom-pill',
      frameText: 'COCTELES',
      frameColor: '#d97706',
      frameTextColor: '#ffffff',
      frameFont: 'display',
      showCard: true,
      cardPosition: 'flyer',
      cardTitle: 'Carta de Cócteles & Destilados',
      cardSubtitle: 'Recetas de autor, destilados prémium y cervezas artesanales',
      cardInstructions: 'Descubre los ingredientes y sabores antes de pedir',
      cardCta: 'Happy Hour todos los días de 19:00 a 21:00 hs',
      cardBgColor: '#111827',
      cardTextColor: '#f9fafb',
      cardBadgeText: 'LOUNGE BAR'
    }
  },
  {
    id: 'coffee-shop-takeaway',
    name: 'Cafetería & Pastelería Artesanal',
    subtitle: 'Tonos café espresso y cálidos para coffee shops y panaderías',
    description: 'Promociona combos de desayuno, café de especialidad y carta de meriendas.',
    category: 'hospitality',
    categoryLabel: 'Restaurantes & Bares',
    badge: '☕ Cafetería',
    icon: '🥐',
    previewColor: '#78350f',
    previewBg: '#fffbeb',
    helperType: 'custom_url',
    sampleUrl: 'https://cafecito.app/menu',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'Café de Especialidad Menú',
      targetContent: 'https://cafecito.app/menu',
      value: 'https://cafecito.app/menu',
      fgColor: '#451a03',
      bgColor: '#fffbeb',
      frameId: 'bottom-banner',
      frameText: 'PEDIR CAFÉ',
      frameColor: '#78350f',
      frameTextColor: '#ffffff',
      frameFont: 'sans',
      showCard: true,
      cardPosition: 'bottom',
      cardTitle: 'Café de Especialidad & Dulces',
      cardSubtitle: 'Tostaduría propia • Leches vegetales • Bollería del día',
      cardInstructions: 'Haz tu pedido o consulta opciones sin gluten',
      cardCta: 'Hecho con pasión cada mañana ☕',
      cardBgColor: '#fffbeb',
      cardTextColor: '#451a03'
    }
  },

  // --- 3. CONECTIVIDAD & WI-FI ---
  {
    id: 'wifi-customers-stand',
    name: 'Wi-Fi Clientes - Conexión Automática',
    subtitle: 'Permite conectar a tus clientes en 1 segundo sin dictar contraseñas',
    description: 'Genera un QR de protocolo Wi-Fi estándar. Al escanearlo, el móvil se conecta automáticamente a la red.',
    category: 'wifi',
    categoryLabel: 'Conexión Wi-Fi',
    badge: '📶 Wi-Fi Gratis',
    icon: '🌐',
    popular: true,
    previewColor: '#4f46e5',
    previewBg: '#ffffff',
    helperType: 'wifi',
    tips: 'Introduce el nombre exacto de tu red Wi-Fi y la contraseña. Los clientes no tendrán que escribir nada.',
    config: {
      contentType: 'WIFI',
      isDynamic: false,
      title: 'Wi-Fi Clientes Cafetería',
      wifiSsid: 'Clientes_Wifi_Gratis',
      wifiPass: 'bienvenido2026',
      targetContent: 'WIFI:S:Clientes_Wifi_Gratis;T:WPA;P:bienvenido2026;;',
      value: 'WIFI:S:Clientes_Wifi_Gratis;T:WPA;P:bienvenido2026;;',
      fgColor: '#1e1b4b',
      bgColor: '#ffffff',
      frameId: 'chat-bubble',
      frameText: 'CONÉCTATE',
      frameColor: '#4f46e5',
      frameTextColor: '#ffffff',
      frameFont: 'sans',
      showCard: true,
      cardPosition: 'flyer',
      cardTitle: 'Wi-Fi Gratuito de Alta Velocidad',
      cardSubtitle: 'Red: Clientes_Wifi_Gratis • Clave: bienvenido2026',
      cardInstructions: '1. Abre tu cámara • 2. Enfoca el código • 3. Toca "Conectar a la red"',
      cardCta: 'Navega gratis y comparte tus fotos en redes sociales',
      cardBgColor: '#ffffff',
      cardTextColor: '#1e1b4b',
      cardBadgeText: 'FREE WI-FI'
    }
  },
  {
    id: 'wifi-airbnb-guest',
    name: 'Wi-Fi Huéspedes - Apartamento / Airbnb',
    subtitle: 'Tarjeta de bienvenida elegante para departamentos turísticos',
    description: 'Evita mensajes de huéspedes preguntando por el Wi-Fi. Cuélgalo o colócalo en el salón.',
    category: 'wifi',
    categoryLabel: 'Conexión Wi-Fi',
    badge: '🏠 Welcome Guest',
    icon: '🔑',
    previewColor: '#0284c7',
    previewBg: '#f0f9ff',
    helperType: 'wifi',
    config: {
      contentType: 'WIFI',
      isDynamic: false,
      title: 'Wi-Fi Guest Apartment',
      wifiSsid: 'Apartment_Guest_5G',
      wifiPass: 'enjoyyourstay2026',
      targetContent: 'WIFI:S:Apartment_Guest_5G;T:WPA;P:enjoyyourstay2026;;',
      value: 'WIFI:S:Apartment_Guest_5G;T:WPA;P:enjoyyourstay2026;;',
      fgColor: '#0c4a6e',
      bgColor: '#f0f9ff',
      frameId: 'smartphone',
      frameText: 'FREE WI-FI',
      frameColor: '#0284c7',
      frameTextColor: '#ffffff',
      frameFont: 'sans',
      showCard: true,
      cardPosition: 'flyer',
      cardTitle: 'Welcome Home! Free Fast Wi-Fi',
      cardSubtitle: 'Network: Apartment_Guest_5G • Fiber 600 Mbps',
      cardInstructions: 'Scan with your smartphone to auto-connect immediately',
      cardCta: 'Have a wonderful stay! Contact host for any questions 🏡',
      cardBgColor: '#ffffff',
      cardTextColor: '#0c4a6e',
      cardBadgeText: 'GUEST NETWORK'
    }
  },

  // --- 4. REDES SOCIALES & MARKETING ---
  {
    id: 'instagram-follow-promo',
    name: 'Instagram - ¡Síguenos & Sorteos!',
    subtitle: 'Aumenta tus seguidores locales en tu tienda o negocio',
    description: 'Lleva directo a tu perfil de Instagram. Ideal para ofrecer cupones o sorteos por seguir la cuenta.',
    category: 'social',
    categoryLabel: 'Redes Sociales',
    badge: '📸 Instagram',
    icon: '✨',
    popular: true,
    previewColor: '#d946ef',
    previewBg: '#ffffff',
    helperType: 'instagram',
    sampleUrl: 'https://instagram.com/tu_marca',
    tips: 'Cambia "tu_marca" por tu nombre de usuario exacto de Instagram.',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'Instagram Síguenos',
      targetContent: 'https://instagram.com/tu_marca',
      value: 'https://instagram.com/tu_marca',
      fgColor: '#701a75',
      bgColor: '#ffffff',
      frameId: 'bottom-pill',
      frameText: 'SÍGUENOS',
      frameColor: '#c026d3',
      frameTextColor: '#ffffff',
      frameFont: 'sans',
      showCard: true,
      cardPosition: 'flyer',
      cardTitle: '¡Síguenos en Instagram!',
      cardSubtitle: '@tu_marca • Novedades, descuentos y sorteos semanales',
      cardInstructions: 'Etiquétanos en tu historia y recibe un 10% OFF',
      cardCta: 'Sube tu foto con el hashtag #MiMarcaFavorita',
      cardBgColor: '#ffffff',
      cardTextColor: '#701a75',
      cardBadgeText: 'INSTAGRAM'
    }
  },
  {
    id: 'whatsapp-direct-chat',
    name: 'WhatsApp - Atención Directa & Pedidos',
    subtitle: 'Inicia una conversación al instante con mensaje predeterminado',
    description: 'Facilita a clientes hacer pedidos, pedir presupuestos o solicitar turnos por WhatsApp.',
    category: 'social',
    categoryLabel: 'Redes Sociales',
    badge: '💬 WhatsApp',
    icon: '📲',
    popular: true,
    previewColor: '#16a34a',
    previewBg: '#f0fdf4',
    helperType: 'whatsapp',
    sampleUrl: 'https://wa.me/34600000000?text=Hola!%20Quisiera%20hacer%20un%20pedido',
    tips: 'Coloca tu número con prefijo internacional sin signos (ej: 34 para España, 54 para Argentina, 52 para México).',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'WhatsApp Atención al Cliente',
      targetContent: 'https://wa.me/34600000000?text=Hola!%20Quisiera%20hacer%20un%20pedido',
      value: 'https://wa.me/34600000000?text=Hola!%20Quisiera%20hacer%20un%20pedido',
      fgColor: '#14532d',
      bgColor: '#f0fdf4',
      frameId: 'chat-bubble',
      frameText: 'WHATSAPP',
      frameColor: '#16a34a',
      frameTextColor: '#ffffff',
      frameFont: 'sans',
      showCard: true,
      cardPosition: 'flyer',
      cardTitle: 'Escríbenos directo por WhatsApp',
      cardSubtitle: 'Atención personalizada • Pedidos rápidos • Consultas al momento',
      cardInstructions: 'Escanea el código y se abrirá el chat con nuestro equipo',
      cardCta: 'Horario de atención: Lunes a Sábado 9:00 a 20:00 hs',
      cardBgColor: '#ffffff',
      cardTextColor: '#14532d',
      cardBadgeText: 'CHAT DIRECTO'
    }
  },
  {
    id: 'tiktok-viral-channel',
    name: 'TikTok - Videos & Comunidad',
    subtitle: 'Moderno estilo neón para creadores de contenido y marcas juveniles',
    description: 'Atrae visitas a tus videos, tutoriales o recetas virales en TikTok.',
    category: 'social',
    categoryLabel: 'Redes Sociales',
    badge: '🎵 TikTok',
    icon: '⚡',
    previewColor: '#000000',
    previewBg: '#f8fafc',
    helperType: 'custom_url',
    sampleUrl: 'https://www.tiktok.com/@tu_cuenta',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'TikTok Canal Oficial',
      targetContent: 'https://www.tiktok.com/@tu_cuenta',
      value: 'https://www.tiktok.com/@tu_cuenta',
      fgColor: '#000000',
      bgColor: '#ffffff',
      frameId: 'bottom-pill',
      frameText: 'TIKTOK',
      frameColor: '#000000',
      frameTextColor: '#ffffff',
      frameFont: 'display',
      showCard: true,
      cardPosition: 'bottom',
      cardTitle: 'Síguenos en TikTok @tu_cuenta',
      cardSubtitle: 'Trends, detrás de escena y consejos diarios',
      cardInstructions: 'Únete a nuestra comunidad de más de 50.000 personas',
      cardCta: 'Nuevos videos todos los días',
      cardBgColor: '#ffffff',
      cardTextColor: '#000000'
    }
  },

  // --- 5. PAGOS, PROPINAS & DONACIONES ---
  {
    id: 'tip-jar-hospitality',
    name: 'Bote de Propinas Digital (Tip Jar)',
    subtitle: 'Permite dejar propina con tarjeta o billetera digital al instante',
    description: 'Excelente para meseros, baristas, músicos callejeros, repartidores y estilistas.',
    category: 'payments',
    categoryLabel: 'Pagos & Propinas',
    badge: '💚 Deja Propina',
    icon: '🪙',
    popular: true,
    previewColor: '#059669',
    previewBg: '#ecfdf5',
    helperType: 'custom_url',
    sampleUrl: 'https://tipjar.app/mi-perfil',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'Propina Digital Staff',
      targetContent: 'https://tipjar.app/mi-perfil',
      value: 'https://tipjar.app/mi-perfil',
      fgColor: '#064e3b',
      bgColor: '#ecfdf5',
      frameId: 'bottom-banner',
      frameText: 'DEJAR PROPINA',
      frameColor: '#059669',
      frameTextColor: '#ffffff',
      frameFont: 'sans',
      showCard: true,
      cardPosition: 'flyer',
      cardTitle: '¿Te ha gustado nuestra atención?',
      cardSubtitle: '¡Agradece a nuestro equipo con una propina digital sin efectivo!',
      cardInstructions: '1. Escanea • 2. Elige el monto que desees • 3. Pago seguro 100%',
      cardCta: '¡Todo el equipo te lo agradece de corazón! 💚',
      cardBgColor: '#ffffff',
      cardTextColor: '#064e3b',
      cardBadgeText: 'TIP JAR'
    }
  },
  {
    id: 'quick-pay-checkout',
    name: 'Punto de Pago Rápido (Bizum / MP / PayPal)',
    subtitle: 'Cobros digitales sin contacto directo a tu pasarela o cuenta',
    description: 'Para puestos de ferias, food trucks, servicios a domicilio y cobros directos.',
    category: 'payments',
    categoryLabel: 'Pagos & Propinas',
    badge: '💳 Paga con QR',
    icon: '💸',
    previewColor: '#0284c7',
    previewBg: '#f8fafc',
    helperType: 'custom_url',
    sampleUrl: 'https://link.mercadopago.com/minuevonegocio',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'Punto de Pago Digital',
      targetContent: 'https://link.mercadopago.com/minuevonegocio',
      value: 'https://link.mercadopago.com/minuevonegocio',
      fgColor: '#075985',
      bgColor: '#ffffff',
      frameId: 'smartphone',
      frameText: 'PAGAR AQUÍ',
      frameColor: '#0284c7',
      frameTextColor: '#ffffff',
      frameFont: 'sans',
      showCard: true,
      cardPosition: 'flyer',
      cardTitle: 'Pago Rápido sin Contacto',
      cardSubtitle: 'Aceptamos transferencias y billeteras virtuales al instante',
      cardInstructions: 'Abre tu app bancaria o cámara para escanear y abonar',
      cardCta: 'Sin recargos adicionales • Transacción segura',
      cardBgColor: '#ffffff',
      cardTextColor: '#075985',
      cardBadgeText: 'PAGO SEGURO'
    }
  },

  // --- 6. BODAS & EVENTOS ---
  {
    id: 'wedding-photos-album',
    name: 'Boda - Sube tus Fotos & Recuerdos',
    subtitle: 'Álbum colaborativo donde los invitados suben sus fotos de la fiesta',
    description: 'Enlaza a Google Drive, Dropbox, Wedbox o iCloud para reunir todas las fotos tomadas en el festejo.',
    category: 'events',
    categoryLabel: 'Bodas & Eventos',
    badge: '💍 Nuestra Boda',
    icon: '💕',
    popular: true,
    previewColor: '#db2777',
    previewBg: '#fff1f2',
    helperType: 'custom_url',
    sampleUrl: 'https://photos.app.goo.gl/sampleAlbumWedding',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'Boda Álbum de Fotos',
      targetContent: 'https://photos.app.goo.gl/sampleAlbumWedding',
      value: 'https://photos.app.goo.gl/sampleAlbumWedding',
      fgColor: '#831843',
      bgColor: '#fff1f2',
      frameId: 'polaroid',
      frameText: 'SUBIR FOTOS',
      frameColor: '#db2777',
      frameTextColor: '#ffffff',
      frameFont: 'serif',
      showCard: true,
      cardPosition: 'flyer',
      cardTitle: '¡Nuestra Boda! Comparte tus Fotos',
      cardSubtitle: 'Ayúdanos a revivir cada momento mágico de esta noche',
      cardInstructions: 'Escanea y sube todas las fotos y videos que tomes',
      cardCta: '¡Gracias por celebrar este día tan especial con nosotros! 💖',
      cardBgColor: '#ffffff',
      cardTextColor: '#831843',
      cardBadgeText: 'LOVE & WEDDING'
    }
  },
  {
    id: 'event-rsvp-confirm',
    name: 'Invitación & Confirmar Asistencia (RSVP)',
    subtitle: 'Formulario de confirmación para bodas, cumpleaños y congresos',
    description: 'Facilita a tus invitados confirmar asistencia, acompañantes y restricciones alimentarias.',
    category: 'events',
    categoryLabel: 'Bodas & Eventos',
    badge: '✉️ Confirmar RSVP',
    icon: '🎉',
    previewColor: '#7c3aed',
    previewBg: '#ffffff',
    helperType: 'custom_url',
    sampleUrl: 'https://forms.gle/sampleRsvpForm',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'Confirmación Asistencia Evento',
      targetContent: 'https://forms.gle/sampleRsvpForm',
      value: 'https://forms.gle/sampleRsvpForm',
      fgColor: '#4c1d95',
      bgColor: '#ffffff',
      frameId: 'bottom-pill',
      frameText: 'CONFIRMAR',
      frameColor: '#7c3aed',
      frameTextColor: '#ffffff',
      frameFont: 'sans',
      showCard: true,
      cardPosition: 'flyer',
      cardTitle: 'Confirmación de Asistencia (RSVP)',
      cardSubtitle: 'Por favor confirma antes del día 15 para organizar las mesas',
      cardInstructions: 'Indica si vienes acompañado y tus preferencias de menú',
      cardCta: '¡Esperamos contar contigo para celebrar a lo grande!',
      cardBgColor: '#ffffff',
      cardTextColor: '#4c1d95',
      cardBadgeText: 'RSVP FORM'
    }
  },

  // --- 7. TIENDAS & DESCUENTOS ---
  {
    id: 'discount-coupon-15off',
    name: 'Cupón de Descuento 15% OFF',
    subtitle: 'Cartel promocional para activar rebajas en caja al escanear',
    description: 'Incentiva la compra inmediata en tiendas físicas o suscripción a newsletter.',
    category: 'retail',
    categoryLabel: 'Tiendas & Promos',
    badge: '🏷️ 15% OFF',
    icon: '🎁',
    popular: true,
    previewColor: '#ea580c',
    previewBg: '#fff7ed',
    helperType: 'custom_url',
    sampleUrl: 'https://mitienda.com/cupon-15',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'Cupón Descuento 15% OFF',
      targetContent: 'https://mitienda.com/cupon-15',
      value: 'https://mitienda.com/cupon-15',
      fgColor: '#7c2d12',
      bgColor: '#fff7ed',
      frameId: 'bottom-banner',
      frameText: '15% DTO',
      frameColor: '#ea580c',
      frameTextColor: '#ffffff',
      frameFont: 'display',
      showCard: true,
      cardPosition: 'flyer',
      cardTitle: '¡15% de Descuento en tu Compra!',
      cardSubtitle: 'Escanea el código para activar tu cupón de bienvenida',
      cardInstructions: 'Muestra la pantalla de tu móvil al momento de abonar en caja',
      cardCta: 'Válido en toda la tienda por tiempo limitado',
      cardBgColor: '#ffffff',
      cardTextColor: '#7c2d12',
      cardBadgeText: 'OFERTA ESPECIAL'
    }
  },
  {
    id: 'ecommerce-catalog-store',
    name: 'Catálogo de Productos Online',
    subtitle: 'Navega stock, tallas y modelos que no están en exhibición física',
    description: 'Multiplica las ventas de tu tienda física conectándola a tu catálogo online completo.',
    category: 'retail',
    categoryLabel: 'Tiendas & Promos',
    badge: '🛍️ Catálogo Web',
    icon: '👗',
    previewColor: '#4f46e5',
    previewBg: '#ffffff',
    helperType: 'custom_url',
    sampleUrl: 'https://mitienda.com/catalogo',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'Catálogo Completo Tienda',
      targetContent: 'https://mitienda.com/catalogo',
      value: 'https://mitienda.com/catalogo',
      fgColor: '#312e81',
      bgColor: '#ffffff',
      frameId: 'bottom-pill',
      frameText: 'CATÁLOGO',
      frameColor: '#4f46e5',
      frameTextColor: '#ffffff',
      frameFont: 'sans',
      showCard: true,
      cardPosition: 'flyer',
      cardTitle: 'Explora Nuestro Catálogo Completo',
      cardSubtitle: 'Nuevos ingresos, tallas disponibles y envíos a todo el país',
      cardInstructions: 'Compra desde tu móvil o pide retiro en este local',
      cardCta: 'Envíos gratis en compras superiores a $50',
      cardBgColor: '#ffffff',
      cardTextColor: '#312e81',
      cardBadgeText: 'NEW COLLECTION'
    }
  },

  // --- 8. PROFESIONALES & CITAS ---
  {
    id: 'vcard-digital-contact',
    name: 'Tarjeta de Contacto Digital (vCard)',
    subtitle: 'Guarda tus datos directamente en la agenda telefónica del cliente',
    description: 'Para ferias, tarjetas de presentación personales, comerciales y directivos.',
    category: 'professional',
    categoryLabel: 'Profesionales & Citas',
    badge: '💼 Contacto vCard',
    icon: '👤',
    popular: true,
    previewColor: '#1e293b',
    previewBg: '#f8fafc',
    helperType: 'vcard',
    tips: 'Configura tu nombre, teléfono y correo. El cliente solo tiene que tocar "Guardar en Contactos".',
    config: {
      contentType: 'VCARD',
      isDynamic: false,
      title: 'Tarjeta de Contacto Profesional',
      vcardName: 'Alejandro Moreno',
      vcardPhone: '+34 612 345 678',
      vcardEmail: 'alejandro@consultoria.com',
      targetContent: 'BEGIN:VCARD\nVERSION:3.0\nN:Moreno;Alejandro\nFN:Alejandro Moreno\nTEL:+34 612 345 678\nEMAIL:alejandro@consultoria.com\nEND:VCARD',
      value: 'BEGIN:VCARD\nVERSION:3.0\nN:Moreno;Alejandro\nFN:Alejandro Moreno\nTEL:+34 612 345 678\nEMAIL:alejandro@consultoria.com\nEND:VCARD',
      fgColor: '#0f172a',
      bgColor: '#ffffff',
      frameId: 'smartphone',
      frameText: 'GUARDAR',
      frameColor: '#1e293b',
      frameTextColor: '#ffffff',
      frameFont: 'sans',
      showCard: true,
      cardPosition: 'flyer',
      cardTitle: 'Tarjeta de Contacto Profesional',
      cardSubtitle: 'Alejandro Moreno • Consultor Estratégico & Asesoría',
      cardInstructions: 'Apunta tu cámara y toca "Añadir a Contactos"',
      cardCta: 'Disponible para reuniones presenciales y videollamadas',
      cardBgColor: '#ffffff',
      cardTextColor: '#0f172a',
      cardBadgeText: 'CONTACT CARD'
    }
  },
  {
    id: 'booking-appointments-clinic',
    name: 'Reserva de Citas & Turnos Online',
    subtitle: 'Para clínicas médicas, consultorios dentales, estética y peluquerías',
    description: 'Evita esperas telefónicas permitiendo a los pacientes reservar su turno en línea.',
    category: 'professional',
    categoryLabel: 'Profesionales & Citas',
    badge: '🩺 Pedir Cita',
    icon: '📅',
    previewColor: '#0891b2',
    previewBg: '#ecfeff',
    helperType: 'custom_url',
    sampleUrl: 'https://miclinica.reservas.com',
    config: {
      contentType: 'URL',
      isDynamic: false,
      title: 'Reserva de Citas Online',
      targetContent: 'https://miclinica.reservas.com',
      value: 'https://miclinica.reservas.com',
      fgColor: '#164e63',
      bgColor: '#ecfeff',
      frameId: 'medical-cross',
      frameText: 'PEDIR CITA',
      frameColor: '#0891b2',
      frameTextColor: '#ffffff',
      frameFont: 'sans',
      showCard: true,
      cardPosition: 'flyer',
      cardTitle: 'Agenda tu Cita Médica Online',
      cardSubtitle: 'Elige profesional, día y horario sin esperas telefónicas',
      cardInstructions: 'Confirmación instantánea por SMS o WhatsApp',
      cardCta: 'Atención personalizada y profesionales especializados',
      cardBgColor: '#ffffff',
      cardTextColor: '#164e63',
      cardBadgeText: 'CITAS ONLINE'
    }
  }
];
